In [ ]:
from scraper.otc.foreign_shareholding.stocks.volume import version_0 as processor

date = '2004/08/04'

session = processor.create_session()
request_info = processor.create_request_info(date)

res = processor.request(session, request_info, 10)

# processor.download_single(session, )

In [1]:
import pathlib
from checker.otc.margin_short.all.stocks_volume_market_volume_value import version_0 as processor

path = pathlib.Path('/Users/youming/Documents/personal/stocklab/playground/data/init/otc/margin_short/all/version0/1st/20030801.html')
content = processor.read(path)

In [1]:
from database.sources.participants.otc.stocks.foreign_trust_dealer_flow_volume import version_2 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/playground/data/init/otc/institution_flow/stocks/version1/1st'
)
# name = '20141201'
# name = '20141128'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

# df = processor.to_df(content)

df = processor.standardize(content, path)

In [2]:
df

,id,foreign_ex_dealer_buy_volume,foreign_ex_dealer_sell_volume,foreign_dealer_buy_volume,foreign_dealer_sell_volume,foreign_buy_volume,foreign_sell_volume,trust_buy_volume,trust_sell_volume,dealer_proprietary_buy_volume,dealer_proprietary_sell_volume,dealer_hedge_buy_volume,dealer_hedge_sell_volume,dealer_buy_volume,dealer_sell_volume,date
0,006201,20000,3102,0,0,20000,3102,0,16000,0,0,239764,375221,239764,375221,2026-04-30
1,00679B,5867000,6203000,0,0,5867000,6203000,0,0,0,0,4572000,6150370,4572000,6150370,2026-04-30
2,00687B,3708000,8540000,0,0,3708000,8540000,0,0,0,10000,12166000,7251107,12166000,7261107,2026-04-30
3,00687C,0,0,0,0,0,0,0,0,0,0,25000,26000,25000,26000,2026-04-30
4,00694B,676000,0,0,0,676000,0,0,0,0,0,19873,643000,19873,643000,2026-04-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901,9949,15000,46000,0,0,15000,46000,0,0,0,0,0,0,0,0,2026-04-30
902,9950,0,1000,0,0,0,1000,0,0,0,0,0,0,0,0,2026-04-30
903,9951,3000,3000,0,0,3000,3000,0,0,0,0,0,0,0,0,2026-04-30
904,9960,97000,0,0,0,97000,0,0,0,0,0,125000,0,125000,0,2026-04-30
905,9962,4000,5000,0,0,4000,5000,0,0,0,0,0,0,0,0,2026-04-30

In [2]:
df.columns.tolist()

['代號',
 '名稱',
 '外資及陸資(不含外資自營商)買進股數',
 '外資及陸資(不含外資自營商)賣出股數',
 '外資及陸資(不含外資自營商)買賣超股數',
 '外資自營商買進股數',
 '外資自營商賣出股數',
 '外資自營商買賣超股數',
 '外資及陸資買進股數',
 '外資及陸資賣出股數',
 '外資及陸資買賣超股數',
 '投信買進股數',
 '投信賣出股數',
 '投信買賣超股數',
 '自營商(自行買賣)買進股數',
 '自營商(自行買賣)賣出股數',
 '自營商(自行買賣)買賣超股數',
 '自營商(避險)買進股數',
 '自營商(避險)賣出股數',
 '自營商(避險)買賣超股數',
 '自營商買進股數',
 '自營商賣出股數',
 '自營商買賣超股數',
 '三大法人買賣超股數合計']

In [3]:
import requests

res = requests.get('https://openapi.tdcc.com.tw/v1/opendata/1-5')

In [5]:
data = res.json()

In [29]:
import pandas as pd

pd.DataFrame(data).set_index('證券代號').loc['1101  ']

       占集保庫存數比例%      人數     ﻿資料日期          股數 持股分級
證券代號
1101        0.27  147115  20260717    20858501    1
1101        6.92  236299  20260717   521246634    2
1101        5.90   59477  20260717   444504057    3
1101        3.96   24084  20260717   298228649    4
1101        3.20   13383  20260717   241286004    5
1101        4.25   12876  20260717   320365928    6
1101        2.73    5854  20260717   205947399    7
1101        2.36    3875  20260717   178140986    8
1101        6.22    6610  20260717   468458281    9
1101        5.13    2802  20260717   386397724   10
1101        4.03    1096  20260717   303408627   11
1101        1.83     285  20260717   138142023   12
1101        1.18     128  20260717    88922935   13
1101        1.04      87  20260717    78767847   14
1101       50.88     412  20260717  3828506147   15
1101        0.00       0  20260717           0   16
1101      100.00  514383  20260717  7523181742   17

In [16]:
i = 1000
data[i*17:(i+1)*17]

[{'證券代號': '2734  ',
  '占集保庫存數比例%': '0.52',
  '人數': '22984',
  '\ufeff資料日期': '20260717',
  '股數': '302937',
  '持股分級': '1'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '15.43',
  '人數': '4408',
  '\ufeff資料日期': '20260717',
  '股數': '8836996',
  '持股分級': '2'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '9.43',
  '人數': '719',
  '\ufeff資料日期': '20260717',
  '股數': '5403600',
  '持股分級': '3'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '4.64',
  '人數': '211',
  '\ufeff資料日期': '20260717',
  '股數': '2657960',
  '持股分級': '4'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '3.84',
  '人數': '121',
  '\ufeff資料日期': '20260717',
  '股數': '2202325',
  '持股分級': '5'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '5.30',
  '人數': '120',
  '\ufeff資料日期': '20260717',
  '股數': '3037107',
  '持股分級': '6'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '4.26',
  '人數': '68',
  '\ufeff資料日期': '20260717',
  '股數': '2443766',
  '持股分級': '7'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '2.38',
  '人數': '29',
  '\ufeff資料日期': '20260717',
  '股數': '1363101',
  '持股分級': '8'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '7.26',
  '人數': '59',
  '\ufeff資料日期': '20260717',
  '股數': '4162062',
  '持股分級': '9'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '4.95',
  '人數': '20',
  '\ufeff資料日期': '20260717',
  '股數': '2837819',
  '持股分級': '10'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '4.51',
  '人數': '10',
  '\ufeff資料日期': '20260717',
  '股數': '2586171',
  '持股分級': '11'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '3.50',
  '人數': '4',
  '\ufeff資料日期': '20260717',
  '股數': '2009141',
  '持股分級': '12'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '2.56',
  '人數': '2',
  '\ufeff資料日期': '20260717',
  '股數': '1467992',
  '持股分級': '13'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '0.00',
  '人數': '0',
  '\ufeff資料日期': '20260717',
  '股數': '0',
  '持股分級': '14'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '31.34',
  '人數': '6',
  '\ufeff資料日期': '20260717',
  '股數': '17948783',
  '持股分級': '15'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '0.00',
  '人數': '0',
  '\ufeff資料日期': '20260717',
  '股數': '0',
  '持股分級': '16'},
 {'證券代號': '2734  ',
  '占集保庫存數比例%': '100.00',
  '人數': '28761',
  '\ufeff資料日期': '20260717',
  '股數': '57259760',
  '持股分級': '17'}]