In [ ]:
# from core.scraper.otc.foreign_shareholding.stocks.volume import url_0 as processor

# date = '2004/08/04'

# session = processor.create_session()
# request_info = processor.create_request_info(date)

# res = processor.request(session, request_info, 10)

# processor.download_single(session, )

In [ ]:
# import pathlib
# from core.checker.otc.margin_short.all.stocks_volume_market_volume_value import url_0 as processor

# path = pathlib.Path('/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/margin_short/all/url_0/1st/20030801.html')
# content = processor.read(path)

In [1]:
from core.database.sources.technicals.twse.stocks.price_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/technicals/stocks/url_0/1st'
)

# name = '20040211'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

raw_df.loc[df.isna().any(axis=1), :]

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
16,00625K,富邦上証+R,0,0,0,--,--,--,--,<p> </p>,0.00,8.73,1,8.87,10,0.00
31,00643K,群益深証中小+R,0,0,0,--,--,--,--,<p> </p>,0.00,4.21,1,4.30,1,0.00
229,020000,富邦特選蘋果N,0,0,0,--,--,--,--,<p> </p>,0.00,25.84,10,25.89,10,0.00
230,020011,統一微波高息20N,0,0,0,--,--,--,--,<p> </p>,0.00,12.14,230,12.16,236,0.00
231,020012,富邦行動通訊N,0,0,0,--,--,--,--,<p> </p>,0.00,20.70,10,20.76,10,0.00
239,020032,元大綠能N,0,0,0,--,--,--,--,<p> </p>,0.00,10.66,150,10.68,150,0.00
241,020036,元大金融配息N,0,0,0,--,--,--,--,<p> </p>,0.00,7.60,150,7.62,150,0.00
282,1312A,國喬特,0,0,0,--,--,--,--,<p> </p>,0.00,22.30,2,22.50,1,0.00
339,1470,大統新創,1,1,22,--,--,--,--,<p> </p>,0.00,22.25,3,23.00,2,28.85
1315,9136,巨騰-DR,0,0,0,--,--,--,--,<p> </p>,0.00,--,,--,,0.00

In [ ]:
from core.database.sources.technicals.twse.market.price import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/technicals/market/price/url_0/1st'
)

# name = '19990301'
name = '20260401'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

        date      open      high       low     close
0 2026-04-01  31892.33  33182.22  31892.33  33174.82
1 2026-04-02  33218.02  33497.58  32516.94  32572.43
2 2026-04-07  32671.52  33264.22  32671.52  33229.82
3 2026-04-08  33379.50  34761.38  33379.50  34761.38
4 2026-04-09  34779.96  34884.45  34617.34  34861.16

In [ ]:
from core.database.sources.technicals.twse.market.volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/technicals/market/volume/url_0/1st'
)

# name = '19900101'
name = '20260401'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

        date     close       volume      turnover   trades
0 2026-04-01  33174.82   9341757628  652608970719  3610783
1 2026-04-02  32572.43  10200475573  702608705100  4542142
2 2026-04-07  33229.82   8303716897  584692254383  3658892
3 2026-04-08  34761.38  12873431242  894100450046  4818400
4 2026-04-09  34861.16  11946350818  872275954561  4973996

In [ ]:
from core.database.sources.technicals.otc.stocks.price_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/technicals/stocks/url_0/1st'
)

# name = '20030801'
# naem = '20040203'
# name = '20041029'
name = '20041126'

path = root.joinpath(name).with_suffix('.html')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

raw_df.loc[df.isna().any(axis=1), :]

       代號  證券名稱   收盤價   開盤價   最高價   最低價 成交股數  成交金額 成交筆數
5    4305  世坤塑膠  ----  ----  ----  ----    0     0    0
11   4406  新昕纖維  ----  ----  ----  ----    0     0    0
41   4706  大恭化學  ----  ----  ----  ----    0     0    0
108  5348  系通科技  ----  ----  ----  ----    0     0    0
119  5385    瑩寶  ----  ----  ----  ----    0     0    0
148  5474  聰泰科技  ----  ----  ----  ----    0     0    0
192  6144  得利影視  ----  ----  ----  ----  523  4392    5
243  6210  慶生電子  ----  ----  ----  ----    0     0    0
319  8087   華鎂光  ----  ----  ----  ----    0     0    0
334  5505  和旺建設  ----  ----  ----  ----    0     0    0
354  5601  台聯貨櫃  ----  ----  ----  ----    0     0    0
361  5703  亞都麗緻  ----  ----  ----  ----    0     0    0
362  5704   老爺知  ----  ----  ----  ----    0     0    0
376  8916    光隆  ----  ----  ----  ----    0     0    0
377  8917    欣泰  ----  ----  ----  ----    0     0    0
379  8923  時報出版  ----  ----  ----  ----    0     0    0

In [ ]:
from core.database.sources.technicals.otc.stocks.price_volume import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/technicals/stocks/url_1/1st'
)

# name = '20070102'
name = '20070420'

path = root.joinpath(name).with_suffix('.html')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

raw_df.loc[df.isna().any(axis=1), :]

,代號,名稱,收盤,漲跌,開盤,最高,最低,均價,成交股數,成交金額(元),成交筆數,最後買價,最後賣價,發行股數,次日參考價,次日漲停價,次日跌停價
0,01006T,基泰SR,0.00,---,0.00,0.00,0.00,-1.00,0,0,0,9.85,9.86,"247,000,000",9.86,10.55,9.17
172,5011,久陽,0.00,---,0.00,0.00,0.00,-1.00,0,0,0,0.00,3.77,"32,437,350",3.77,4.03,3.51
220,5386,青雲,0.00,---,0.00,0.00,0.00,5.31,999,"5,303",3,0.00,5.60,"23,603,789",5.70,6.09,5.31
224,5395,普揚,0.00,---,0.00,0.00,0.00,34.43,14,482,1,0.00,36.70,"28,523,500",37.00,39.55,34.45
430,70183,中信R6,0.00,---,0.00,0.00,0.00,-1.00,0,0,0,0.02,0.03,"60,000,000",0.04,0.13,0.01
435,70193,中信R7,☉ 0.01,0.00,0.00,0.00,0.00,-1.00,0,0,0,0.00,0.01,"5,000,000",0.01,1.86,0.01
436,70194,中信R8,☉ 0.01,0.00,0.00,0.00,0.00,-1.00,0,0,0,0.00,0.01,"12,000,000",0.01,0.76,0.01
441,70199P,中信S1,☉ 0.01,0.00,0.00,0.00,0.00,-1.00,0,0,0,0.00,0.01,"20,000,000",0.01,2.80,0.01
450,70209,中信S3,☉ 0.01,0.00,0.00,0.00,0.00,-1.00,0,0,0,0.00,0.01,"60,000,000",0.01,0.10,0.01
675,8917,欣泰,0.00,---,0.00,0.00,0.00,33.10,211,"6,984",2,34.05,34.50,"80,182,875",34.80,37.20,32.40
676,8921,沈氏,0.00,---,0.00,0.00,0.00,-1.00,0,0,0,10.95,11.25,"47,421,159",11.00,11.75,10.25
687,8934,喬工,0.00,---,0.00,0.00,0.00,-1.00,0,0,0,0.00,0.00,"18,515,500",2.41,2.57,2.25

In [ ]:
from core.database.sources.technicals.otc.stocks.price_volume import version_2 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/technicals/stocks/url_2/1st'
)

# name = '20070423'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

raw_df.loc[df.isna().any(axis=1), :]

,代號,名稱,收盤,漲跌,開盤,最高,最低,均價,成交股數,成交金額(元),成交筆數,最後買價,最後買量(張數),最後賣價,最後賣量(張數),發行股數,次日 參考價,次日 漲停價,次日 跌停價
118,020035,元大上櫃ESG高息N,---,---,---,---,---,12.04,0,0,0,12.00,150,12.02,150,"200,000,000",12.02,13.22,10.82
156,2073,雄順,---,---,---,---,---,26.24,0,0,0,24.90,1,26.50,2,"27,500,000",26.30,28.90,23.70
181,2924,宏太-KY,---,---,---,---,---,21.55,0,0,0,19.45,2,21.55,1,"52,035,934",21.55,23.70,19.40
230,3226,龍鋒,---,---,---,---,---,41.26,31,"1,279",3,40.50,1,41.50,1,"64,430,573",41.50,45.65,37.35
435,4568,科際精密,---,---,---,---,---,43.50,50,"2,175",1,40.95,1,41.30,1,"31,730,125",41.30,45.40,37.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10276,8077,洛碁,---,---,---,---,---,42.07,0,0,0,41.90,1,43.20,1,"21,945,669",42.00,46.20,37.80
10313,8342,益張,---,---,---,---,---,85.06,160,"13,609",26,88.10,1,90.00,1,"33,536,692",88.20,97.00,79.40
10315,8349A,恒耀甲特,---,---,---,---,---,47.30,0,0,0,47.25,1,47.50,1,"10,000,000",47.30,52.00,42.60
10349,8921,沈氏,---,---,---,---,---,18.67,0,0,0,17.25,1,18.55,2,"46,592,159",18.55,20.40,16.70
10350,8923,時報,---,---,---,---,---,19.00,1,19,1,19.10,2,19.50,2,"30,375,800",19.50,21.45,17.55

In [ ]:
from core.database.sources.technicals.otc.market.price import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/technicals/market/price/url_0/1st'
)

# name = '19990901'
name = '20260401'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

        date    open    high     low   close
0 2026-04-01  309.50  321.90  309.50  321.19
1 2026-04-02  321.61  327.12  317.77  317.90
2 2026-04-07  318.81  326.69  318.81  325.61
3 2026-04-08  326.79  341.20  326.79  341.20
4 2026-04-09  341.51  345.83  341.51  342.57

In [ ]:
from core.database.sources.technicals.otc.market.volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/technicals/market/volume/url_0/1st'
)

# name = '19990101'
name = '20241201'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

        date   close      volume      turnover  trades
0 2024-12-02  257.84  1012784000   98828261000  732769
1 2024-12-03  259.11   860506000   98091770000  691122
2 2024-12-04  262.60  1157493000  114754381000  836368
3 2024-12-05  263.39  1321873000  126040990000  943926
4 2024-12-06  261.52   927371000   97764081000  774009

In [ ]:
from core.database.sources.technicals.otc.market.volume import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/technicals/market/volume/url_0/1st'
)

# name = '20250101'
name = '20260401'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

        date   close      volume      turnover   trades
0 2026-04-01  321.19   753759000  147919030000   751749
1 2026-04-02  317.90   831792000  179853553000   848798
2 2026-04-07  325.61   806265000  167715379000   830353
3 2026-04-08  341.20   982334000  209607993000   965291
4 2026-04-09  342.57  1308235000  250323691000  1263393

In [ ]:
from core.database.sources.positions.twse.stocks.margin_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/margin_short/all/url_0/1st'
)

# name = '20010102'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,margin_buy_volume,margin_sell_volume,margin_cash_repayment_volume,margin_balance_volume,margin_next_day_limit_volume,date
0,00400A,912000,2009000,17000,12827000,363785000,2026-04-30
1,00401A,488000,56000,0,1597000,68348000,2026-04-30
2,0050,335000,821000,21000,9569000,4623750000,2026-04-30
3,0051,0,15000,0,2000,6125000,2026-04-30
4,0052,497000,1112000,19000,11185000,628625000,2026-04-30

In [ ]:
from core.database.sources.positions.twse.stocks.short_sbl_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/short_sbl/stocks/volume/url_0/1st'
)

# name = '20050701'
name = '20120316'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,short_sell_volume,short_cover_volume,short_stock_repayment_volume,short_balance_volume,short_next_day_limit_volume,sbl_sell_volume,sbl_ex_sell_change_volume,sbl_balance_volume,sbl_next_day_limit_volume,date
0,0015,0,0,0,0,125000000,0,0,0,32060,2012-03-16
1,0050,4000,39000,0,6422000,389875000,0,0,3820000,4124967,2012-03-16
2,0051,6000,0,0,93000,9000000,0,0,0,57534,2012-03-16
3,0052,0,0,0,0,3375000,0,0,0,2693,2012-03-16
4,0053,0,0,0,0,10247000,0,0,0,7506,2012-03-16

In [ ]:
from core.database.sources.positions.twse.stocks.short_sbl_volume import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/short_sbl/stocks/volume/url_0/1st'
)

# name = '20120319'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,short_sell_volume,short_cover_volume,short_stock_repayment_volume,short_balance_volume,short_next_day_limit_volume,sbl_sell_volume,sbl_return_volume,sbl_adjustment_volume,sbl_balance_volume,sbl_next_day_limit_volume,date,sbl_ex_sell_change_volume
0,00400A,36000,0,0,43000,363785000,0,485000,0,10417000,35922411,2026-04-30,-485000
1,00401A,0,0,0,0,68348750,0,2400000,0,639000,7269150,2026-04-30,-2400000
2,0050,40000,50000,0,1498000,4623750000,14612000,2506000,0,112828000,36885265,2026-04-30,-2506000
3,0051,0,0,0,0,6125000,0,0,0,658000,32511,2026-04-30,0
4,0052,8000,58000,0,79000,628625000,0,0,0,27014000,15015172,2026-04-30,0

In [ ]:
from core.database.sources.positions.twse.stocks.short_sbl_value import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/short_sbl/stocks/value/url_0/1st'
)

# name = '20080926'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

       id  short_sell_value  sbl_sell_value       date
0  00400A            465930               0 2026-04-30
1  00401A                 0               0 2026-04-30
2    0050           3638950      1328389000 2026-04-30
3    0051                 0               0 2026-04-30
4    0052            423450               0 2026-04-30

In [ ]:
from core.database.sources.positions.twse.market.margin_volume_value import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/margin_short/all/url_0/1st'
)

# name = '20010102'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,margin_buy_volume,margin_sell_volume,margin_cash_repayment_volume,margin_balance_volume,margin_buy_value,margin_sell_value,margin_cash_repayment_value,margin_balance_value,date
0,425023000,407553000,9627000,8680623000,36514008000,36037931000,546303000,460904578000,2026-04-30

In [ ]:
from core.database.sources.positions.twse.market.short_sbl_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/short_sbl/stocks/volume/url_0/1st'
)

# name = '20050701'
name = '20120316'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,short_sell_volume,short_cover_volume,short_stock_repayment_volume,short_balance_volume,sbl_sell_volume,sbl_ex_sell_change_volume,sbl_balance_volume,date
0,39578000,37007000,7565000,588041000,21788000,-16234750,2969515742,2012-03-16

In [ ]:
from core.database.sources.positions.twse.market.short_sbl_volume import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/short_sbl/stocks/volume/url_0/1st'
)

# name = '20120319'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,short_sell_volume,short_cover_volume,short_stock_repayment_volume,short_balance_volume,sbl_sell_volume,sbl_return_volume,sbl_adjustment_volume,sbl_balance_volume,date,sbl_ex_sell_change_volume
0,30232000,16191000,4758000,206703000,358213000,224288815,0,18266419590,2026-04-30,-224288815

In [ ]:
from core.database.sources.positions.twse.market.short_sbl_value import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/short_sbl/stocks/value/url_0/1st'
)

# name = '20080926'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

   short_sell_value  sbl_sell_value       date
0        2524885979     32437046770 2026-04-30

In [ ]:
from core.database.sources.positions.otc.stocks.margin_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/margin_short/all/url_0/1st'
)

# name = '20030801'
# name = '20041027'
name = '20061229'

path = root.joinpath(name).with_suffix('.html')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,margin_buy_volume,margin_sell_volume,margin_cash_repayment_volume,margin_balance_volume,margin_next_day_limit_volume,date
5,1333,277000,350000,0,8639000,20250000,2006-12-29
6,1565,0,88000,0,924000,11908000,2006-12-29
7,1569,1000,3000,0,451000,12294000,2006-12-29
8,1570,27000,28000,10000,1439000,10615000,2006-12-29
9,1781,44000,55000,0,1283000,8696000,2006-12-29

In [ ]:
from core.database.sources.positions.otc.stocks.margin_volume import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/margin_short/all/url_1/1st'
)

# name = '20070102'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,margin_buy_volume,margin_sell_volume,margin_cash_repayment_volume,margin_balance_volume,margin_next_day_limit_volume,date
0,00679B,78000,0,1000,5116000,1865298000,2026-04-30
1,00687B,2983000,1000,6000,11163000,1430658000,2026-04-30
2,00694B,0,0,0,0,43644000,2026-04-30
3,00695B,0,0,0,0,9671000,2026-04-30
4,00696B,0,0,0,141000,173045000,2026-04-30

In [ ]:
from core.database.sources.positions.otc.stocks.short_sbl_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/short_sbl/stocks/volume/url_0/1st'
)

# name = '20060102'
name = '20120316'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

raw_df.loc[df.isna().any(axis=1), :]

Empty DataFrame
Columns: [股票代號, 融券前日餘額, 融券賣出, 融券買進, 融券現券, 融券今日餘額, 融券限額, 借券前日餘額, 借券賣出, 借券庫存異動, 借券今日餘額, 借券可使用額度, 備註]
Index: []

In [ ]:
from core.database.sources.positions.otc.stocks.short_sbl_volume import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/short_sbl/stocks/volume/url_1/1st'
)

# name = '20120319'
name = '20121001'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,short_sell_volume,short_cover_volume,short_stock_repayment_volume,short_balance_volume,short_next_day_limit_volume,sbl_sell_volume,sbl_return_volume,sbl_adjustment_volume,sbl_balance_volume,sbl_next_day_limit_volume,date,sbl_ex_sell_change_volume
0,006201,0,0,0,0,18986500,0,0,0,0,45966,2012-03-19,0
1,006202,0,0,0,0,1999750,0,0,0,0,4866,2012-03-19,0
2,1336,0,0,0,0,16563308,0,0,0,0,16248,2012-03-19,0
3,1558,1000,0,0,19000,11792293,0,0,0,20000,79275,2012-03-19,0
4,1565,0,2000,0,37000,12604129,0,0,0,47000,65648,2012-03-19,0

In [ ]:
from core.database.sources.positions.otc.stocks.short_sbl_volume import version_2 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/short_sbl/stocks/volume/url_2/1st'
)

# name = '20121002'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,short_sell_volume,short_cover_volume,short_stock_repayment_volume,short_balance_volume,short_next_day_limit_volume,sbl_sell_volume,sbl_return_volume,sbl_adjustment_volume,sbl_balance_volume,sbl_next_day_limit_volume,date,sbl_ex_sell_change_volume
0,006201,2000,0,0,10000,5111500,7000,0,0,136000,158844,2026-04-30,0
1,00679B,0,0,0,16000,1865298000,100000,0,0,93145000,11674835,2026-04-30,0
2,00687B,7000,0,0,12000,1430658731,105000,0,0,44577000,7963627,2026-04-30,0
3,00694B,0,0,0,0,43644000,0,0,0,111000,121808,2026-04-30,0
4,00695B,0,0,0,0,9671500,0,0,0,320000,62321,2026-04-30,0

In [ ]:
from core.database.sources.positions.otc.stocks.short_sbl_value import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/short_sbl/stocks/value/url_0/1st'
)

# name = '20081001'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

       id  short_sell_value  sbl_sell_value       date
0  00679B                 0         2682000 2026-04-30
1  00687B            194950         2925300 2026-04-30
2  00687C                 0               0 2026-04-30
3  00694B                 0               0 2026-04-30
4  00695B                 0               0 2026-04-30

In [ ]:
from core.database.sources.positions.otc.market.margin_volume_value import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/margin_short/all/url_0/1st'
)

# name = '20030801'
# name = '20041027'
name = '20061229'

path = root.joinpath(name).with_suffix('.html')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,margin_buy_volume,margin_sell_volume,margin_cash_repayment_volume,margin_balance_volume,margin_buy_value,margin_sell_value,margin_cash_repayment_value,margin_balance_value,date
0,277171000,267011000,5145000,4429219000,5014351000,4565328000,79100000,71574884000,2006-12-29

In [ ]:
from core.database.sources.positions.otc.market.margin_volume_value import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/margin_short/all/url_1/1st'
)

# name = '20070102'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,margin_buy_volume,margin_sell_volume,margin_cash_repayment_volume,margin_balance_volume,margin_buy_value,margin_sell_value,margin_cash_repayment_value,margin_balance_value,date
0,119308000,111821000,2130000,2312171000,16334168000,14412511000,184360000,180438401000,2026-04-30

In [ ]:
from core.database.sources.positions.otc.market.short_sbl_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/short_sbl/stocks/volume/url_0/1st'
)

# name = '20060102'
name = '20120316'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,short_sell_volume,short_cover_volume,short_stock_repayment_volume,short_balance_volume,sbl_sell_volume,sbl_ex_sell_change_volume,sbl_balance_volume,date
0,7050000,4882000,1822000,106669000,92000,354000,139832277,2012-03-16

In [ ]:
from core.database.sources.positions.otc.market.short_sbl_volume import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/short_sbl/stocks/volume/url_1/1st'
)

# name = '20120319'
name = '20121001'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,short_sell_volume,short_cover_volume,short_stock_repayment_volume,short_balance_volume,sbl_sell_volume,sbl_return_volume,sbl_adjustment_volume,sbl_balance_volume,date,sbl_ex_sell_change_volume
0,3394000,2190000,959000,82218000,2273000,284000,0,117791150,2012-10-01,-284000

In [ ]:
from core.database.sources.positions.otc.market.short_sbl_volume import version_2 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/short_sbl/stocks/volume/url_2/1st'
)

# name = '20121002'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,short_sell_volume,short_cover_volume,short_stock_repayment_volume,short_balance_volume,sbl_sell_volume,sbl_return_volume,sbl_adjustment_volume,sbl_balance_volume,date,sbl_ex_sell_change_volume
0,4744000,3053000,930000,27703000,39981000,23491539,0,1821139593,2026-04-30,-23491539

In [ ]:
from core.database.sources.positions.otc.market.short_sbl_value import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/short_sbl/stocks/value/url_0/1st'
)

# name = '20081001'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

   short_sell_value  sbl_sell_value       date
0        1519227364      7954515570 2026-04-30

In [ ]:
from core.database.sources.participants.twse.stocks.foreign_trust_dealer_flow_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/institution_flow/stocks/url_0/1st'
)

# name = '20120502'
name = '20141128'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

Empty DataFrame
Columns: [證券代號, 證券名稱, 外資買進股數, 外資賣出股數, 外資買賣超股數, 投信買進股數, 投信賣出股數, 投信買賣超股數, 自營商買賣超股數, 自營商買進股數, 自營商賣出股數, 三大法人買賣超股數]
Index: []

In [ ]:
from core.database.sources.participants.twse.stocks.foreign_trust_dealer_flow_volume import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/institution_flow/stocks/url_0/1st'
)

# name = '20141201'
name = '20171215'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,foreign_buy_volume,foreign_sell_volume,trust_buy_volume,trust_sell_volume,dealer_proprietary_buy_volume,dealer_proprietary_sell_volume,dealer_hedge_buy_volume,dealer_hedge_sell_volume,date,dealer_buy_volume,dealer_sell_volume
0,00632R,18769000,148000,0,0,960000,1000000,3080000,6394000,2017-12-15,4040000,7394000
1,2891,23931016,33135548,18652000,0,267000,0,415000,34000,2017-12-15,682000,34000
2,2371,7768514,12977000,75000,3000,1715000,22000,13208000,1120000,2017-12-15,14923000,1142000
3,1704,2814000,5649170,8042000,1000,309000,390000,74000,383000,2017-12-15,383000,773000
4,2618,9504856,6088667,0,3000,320000,14000,941000,485000,2017-12-15,1261000,499000

In [ ]:
from core.database.sources.participants.twse.stocks.foreign_trust_dealer_flow_volume import version_2 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/institution_flow/stocks/url_0/1st'
)

# name = '20171218'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,foreign_ex_dealer_buy_volume,foreign_ex_dealer_sell_volume,foreign_dealer_buy_volume,foreign_dealer_sell_volume,trust_buy_volume,trust_sell_volume,dealer_proprietary_buy_volume,dealer_proprietary_sell_volume,dealer_hedge_buy_volume,dealer_hedge_sell_volume,date,foreign_buy_volume,foreign_sell_volume,dealer_buy_volume,dealer_sell_volume
0,00981A,103128651,74274800,0,0,0,0,2054000,2593000,67153643,39728689,2026-04-30,103128651,74274800,69207643,42321689
1,00919,17477735,18812264,0,0,0,0,400000,0,51326911,7293501,2026-04-30,17477735,18812264,51726911,7293501
2,00878,25971928,6287985,0,0,0,0,0,15000,30138210,9573260,2026-04-30,25971928,6287985,30138210,9588260
3,2303,160025515,120833736,0,0,3144000,9300269,1164574,454341,3475192,2053907,2026-04-30,160025515,120833736,4639766,2508248
4,00940,7628000,5378072,0,0,0,0,0,0,29212359,2322000,2026-04-30,7628000,5378072,29212359,2322000

In [ ]:
from core.database.sources.participants.twse.stocks.foreign_balance_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/foreign_shareholding/stocks/url_0/1st'
)

# name = '20040211'
name = '20090430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,total_outstanding_shares,foreign_balance_volume,foreign_volume_limit_ratio,date
0,0015,500000000,237118000,100.0,2009-04-30
1,0050,1246500000,269467238,100.0,2009-04-30
2,0051,44000000,640000,100.0,2009-04-30
3,0052,27000000,134000,100.0,2009-04-30
4,0053,67988000,103000,100.0,2009-04-30

In [ ]:
from core.database.sources.participants.twse.stocks.foreign_balance_volume import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/foreign_shareholding/stocks/url_0/1st'
)

# name = '20090504'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,total_outstanding_shares,foreign_balance_volume,foreign_volume_limit_ratio,date
0,00400A,1455140000,59670734,100.0,2026-04-30
1,00401A,273395000,9681335,100.0,2026-04-30
2,0050,18495000000,654067308,100.0,2026-04-30
3,0051,24500000,140088,100.0,2026-04-30
4,0052,2514500000,52250298,100.0,2026-04-30

In [ ]:
from core.database.sources.participants.twse.market.foreign_trust_dealer_flow_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/institution_flow/stocks/url_0/1st'
)

# name = '20120502'
name = '20141128'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,foreign_buy_volume,foreign_sell_volume,trust_buy_volume,trust_sell_volume,dealer_buy_volume,dealer_sell_volume,date
0,409197264,305613469,45884000,15753287,143762455,128966427,2014-11-28

In [ ]:
from core.database.sources.participants.twse.market.foreign_trust_dealer_flow_volume import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/institution_flow/stocks/url_0/1st'
)

# name = '20141201'
name = '20171215'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,foreign_buy_volume,foreign_sell_volume,trust_buy_volume,trust_sell_volume,dealer_proprietary_buy_volume,dealer_proprietary_sell_volume,dealer_hedge_buy_volume,dealer_hedge_sell_volume,date,dealer_buy_volume,dealer_sell_volume
0,894678336,996511515,84619600,66609257,16755999,16954055,73586055,127523506,2017-12-15,90342054,144477561

In [ ]:
from core.database.sources.participants.twse.market.foreign_trust_dealer_flow_volume import version_2 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/institution_flow/stocks/url_0/1st'
)

# name = '20171218'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,foreign_ex_dealer_buy_volume,foreign_ex_dealer_sell_volume,foreign_dealer_buy_volume,foreign_dealer_sell_volume,trust_buy_volume,trust_sell_volume,dealer_proprietary_buy_volume,dealer_proprietary_sell_volume,dealer_hedge_buy_volume,dealer_hedge_sell_volume,date,foreign_buy_volume,foreign_sell_volume,dealer_buy_volume,dealer_sell_volume
0,2358297497,2595489067,0,0,34773247,138105599,41163956,45519075,805511647,883075593,2026-04-30,2358297497,2595489067,846675603,928594668

In [ ]:
from core.database.sources.participants.twse.market.foreign_balance_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/foreign_shareholding/stocks/url_0/1st'
)

# name = '20040211'
name = '20090430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

   total_outstanding_shares  foreign_balance_volume       date
0              581339772198            128850074835 2009-04-30

In [ ]:
from core.database.sources.participants.twse.market.foreign_balance_volume import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/foreign_shareholding/stocks/url_0/1st'
)

# name = '20090504'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

   total_outstanding_shares  foreign_balance_volume       date
0              994921979950            170092844946 2026-04-30

In [ ]:
from core.database.sources.participants.twse.market.foreign_trust_dealer_flow_value import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/institution_flow/market/url_0/1st'
)

# name = '20040407'
name = '20090430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,foreign_buy_value,foreign_sell_value,trust_buy_value,trust_sell_value,dealer_buy_value,dealer_sell_value,date
0,46411259708,13416499870,3393631960,2093381562,2704871070,1563506048,2009-04-30

In [ ]:
from core.database.sources.participants.twse.market.foreign_trust_dealer_flow_value import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/institution_flow/market/url_0/1st'
)

# name = '20090504'
name = '20141128'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,foreign_buy_value,foreign_sell_value,trust_buy_value,trust_sell_value,dealer_buy_value,dealer_sell_value,date
0,20263355608,14562642727,1432105850,854725385,5801845384,5816247183,2014-11-28

In [ ]:
from core.database.sources.participants.twse.market.foreign_trust_dealer_flow_value import version_2 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/institution_flow/market/url_0/1st'
)

# name = '20141201'
name = '20171215'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,foreign_buy_value,foreign_sell_value,trust_buy_value,trust_sell_value,dealer_proprietary_buy_value,dealer_proprietary_sell_value,dealer_hedge_buy_value,dealer_hedge_sell_value,date,dealer_buy_value,dealer_sell_value
0,46753892254,51034339314,3438839098,3585595276,730982985,1018702931,3700310104,6402695186,2017-12-15,4431293089,7421398117

In [ ]:
from core.database.sources.participants.twse.market.foreign_trust_dealer_flow_value import version_3 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/twse/institution_flow/market/url_0/1st'
)

# name = '20171218'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,foreign_ex_dealer_buy_value,foreign_ex_dealer_sell_value,foreign_dealer_buy_value,foreign_dealer_sell_value,trust_buy_value,trust_sell_value,dealer_proprietary_buy_value,dealer_proprietary_sell_value,dealer_hedge_buy_value,dealer_hedge_sell_value,date,dealer_buy_value,dealer_sell_value,foreign_buy_value,foreign_sell_value
0,406259095898,459820821006,0,0,14855053761,13771840985,6267791666,7078094179,33731823451,33710390522,2026-04-30,39999615117,40788484701,406259095898,459820821006

In [ ]:
from core.database.sources.participants.otc.stocks.foreign_trust_dealer_flow_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/institution_flow/stocks/url_0/1st'
)

# name = '20070423'
name = '20141128'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,foreign_buy_volume,foreign_sell_volume,trust_buy_volume,trust_sell_volume,dealer_buy_volume,dealer_sell_volume,date
0,006201,0,0,0,0,0,33000,2014-11-28
1,1558,27000,0,0,10000,3000,1665,2014-11-28
2,1565,204000,130000,0,0,7000,12000,2014-11-28
3,1566,2000,0,0,0,0,0,2014-11-28
4,1580,7000,9000,0,11000,1000,0,2014-11-28

In [ ]:
from core.database.sources.participants.otc.stocks.foreign_trust_dealer_flow_volume import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/institution_flow/stocks/url_1/1st'
)

# name = '20141201'
name = '20180112'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,foreign_buy_volume,foreign_sell_volume,trust_buy_volume,trust_sell_volume,dealer_proprietary_buy_volume,dealer_proprietary_sell_volume,dealer_hedge_buy_volume,dealer_hedge_sell_volume,date,dealer_buy_volume,dealer_sell_volume
0,006201,0,0,0,0,0,0,36000,8000,2018-01-12,36000,8000
1,00679B,0,0,0,0,0,0,0,3520000,2018-01-12,0,3520000
2,00687B,0,0,0,0,0,0,400000,401000,2018-01-12,400000,401000
3,00694B,0,0,0,0,0,0,500000,500000,2018-01-12,500000,500000
4,00695B,0,0,0,0,0,0,500000,501000,2018-01-12,500000,501000

In [ ]:
from core.database.sources.participants.otc.stocks.foreign_trust_dealer_flow_volume import version_2 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/institution_flow/stocks/url_1/1st'
)

# name = '20180115'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,foreign_ex_dealer_buy_volume,foreign_ex_dealer_sell_volume,foreign_dealer_buy_volume,foreign_dealer_sell_volume,foreign_buy_volume,foreign_sell_volume,trust_buy_volume,trust_sell_volume,dealer_proprietary_buy_volume,dealer_proprietary_sell_volume,dealer_hedge_buy_volume,dealer_hedge_sell_volume,dealer_buy_volume,dealer_sell_volume,date
0,006201,20000,3102,0,0,20000,3102,0,16000,0,0,239764,375221,239764,375221,2026-04-30
1,00679B,5867000,6203000,0,0,5867000,6203000,0,0,0,0,4572000,6150370,4572000,6150370,2026-04-30
2,00687B,3708000,8540000,0,0,3708000,8540000,0,0,0,10000,12166000,7251107,12166000,7261107,2026-04-30
3,00687C,0,0,0,0,0,0,0,0,0,0,25000,26000,25000,26000,2026-04-30
4,00694B,676000,0,0,0,676000,0,0,0,0,0,19873,643000,19873,643000,2026-04-30

In [ ]:
from core.database.sources.participants.otc.stocks.foreign_balance_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/foreign_shareholding/stocks/url_0/1st'
)

# name = '20040804'
name = '20100115'

path = root.joinpath(name).with_suffix('.html')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,total_outstanding_shares,foreign_balance_volume,foreign_volume_limit_ratio,date
0,1336,66253230,155282,100.0,2010-01-15
1,1565,50416516,17715848,100.0,2010-01-15
2,1569,60865065,178404,100.0,2010-01-15
3,1570,51500839,19910,100.0,2010-01-15
4,1580,36928500,66000,100.0,2010-01-15

In [ ]:
from core.database.sources.participants.otc.stocks.foreign_balance_volume import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/foreign_shareholding/stocks/url_0/1st'
)

# name = '20100118'
name = '20260430'

path = root.joinpath(name).with_suffix('.html')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,id,total_outstanding_shares,foreign_balance_volume,foreign_volume_limit_ratio,date
0,006201,20446000,257481,100.0,2026-04-30
1,00679B,7461192000,331034558,100.0,2026-04-30
2,00687B,5722634927,491061198,100.0,2026-04-30
3,00687C,2012268,0,100.0,2026-04-30
4,00694B,174576000,3355872,100.0,2026-04-30

In [ ]:
from core.database.sources.participants.otc.market.foreign_trust_dealer_flow_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/institution_flow/stocks/url_0/1st'
)

# name = '20070423'
name = '20141128'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,foreign_buy_volume,foreign_sell_volume,trust_buy_volume,trust_sell_volume,dealer_buy_volume,dealer_sell_volume,date
0,15591150,11157241,2146000,6917047,5804000,8991263,2014-11-28

In [ ]:
from core.database.sources.participants.otc.market.foreign_trust_dealer_flow_volume import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/institution_flow/stocks/url_1/1st'
)

# name = '20141201'
name = '20180112'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,foreign_buy_volume,foreign_sell_volume,trust_buy_volume,trust_sell_volume,dealer_proprietary_buy_volume,dealer_proprietary_sell_volume,dealer_hedge_buy_volume,dealer_hedge_sell_volume,date,dealer_buy_volume,dealer_sell_volume
0,40232717,34317467,5926000,3119654,4799000,3292390,13298000,14868025,2018-01-12,18097000,18160415

In [ ]:
from core.database.sources.participants.otc.market.foreign_trust_dealer_flow_volume import version_2 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/institution_flow/stocks/url_1/1st'
)

# name = '20180115'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,foreign_ex_dealer_buy_volume,foreign_ex_dealer_sell_volume,foreign_dealer_buy_volume,foreign_dealer_sell_volume,foreign_buy_volume,foreign_sell_volume,trust_buy_volume,trust_sell_volume,dealer_proprietary_buy_volume,dealer_proprietary_sell_volume,dealer_hedge_buy_volume,dealer_hedge_sell_volume,dealer_buy_volume,dealer_sell_volume,date
0,358093842,399110906,0,0,358093842,399110906,15462091,10064307,4104583,5782560,123379957,135920047,127484540,141702607,2026-04-30

In [ ]:
from core.database.sources.participants.otc.market.foreign_balance_volume import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/foreign_shareholding/stocks/url_0/1st'
)

# name = '20040804'
name = '20100115'

path = root.joinpath(name).with_suffix('.html')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

   total_outstanding_shares  foreign_balance_volume       date
0               42683574245              2498367987 2010-01-15

In [ ]:
from core.database.sources.participants.otc.market.foreign_balance_volume import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/foreign_shareholding/stocks/url_0/1st'
)

# name = '20100118'
name = '20260430'

path = root.joinpath(name).with_suffix('.html')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

   total_outstanding_shares  foreign_balance_volume       date
0              203644796832             11534398877 2026-04-30

In [ ]:
from core.database.sources.participants.otc.market.foreign_trust_dealer_flow_value import version_0 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/institution_flow/market/url_0/1st'
)

# name = '20040601'
name = '20061229'

path = root.joinpath(name).with_suffix('.html')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,foreign_buy_value,foreign_sell_value,trust_buy_value,trust_sell_value,dealer_buy_value,dealer_sell_value,date
0,851700581,1168833636,1343175500,1034407914,1763995040,1443033496,2006-12-29

In [ ]:
from core.database.sources.participants.otc.market.foreign_trust_dealer_flow_value import version_1 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/institution_flow/market/url_1/1st'
)

# name = '20070102'
name = '20090703'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,foreign_buy_value,foreign_sell_value,trust_buy_value,trust_sell_value,dealer_buy_value,dealer_sell_value,date
0,684783978,399590137,1290743750,314259840,602348384,284253610,2009-07-03

In [ ]:
from core.database.sources.participants.otc.market.foreign_trust_dealer_flow_value import version_2 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/institution_flow/market/url_1/1st'
)

# name = '20090706'
name = '20141128'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,foreign_buy_value,foreign_sell_value,trust_buy_value,trust_sell_value,dealer_buy_value,dealer_sell_value,date
0,1567043605,1026026159,290632600,501786846,656571430,974677853,2014-11-28

In [ ]:
from core.database.sources.participants.otc.market.foreign_trust_dealer_flow_value import version_3 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/institution_flow/market/url_1/1st'
)

# name = '20141201'
name = '20161230'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,foreign_buy_value,foreign_sell_value,trust_buy_value,trust_sell_value,dealer_proprietary_buy_value,dealer_proprietary_sell_value,dealer_hedge_buy_value,dealer_hedge_sell_value,dealer_buy_value,dealer_sell_value,date
0,1328718136,1240660317,374020950,290372000,164094250,144724570,405751350,419609345,569845600,564333915,2016-12-30

In [ ]:
from core.database.sources.participants.otc.market.foreign_trust_dealer_flow_value import version_4 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/institution_flow/market/url_1/1st'
)

# name = '20170103'
name = '20180111'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,trust_buy_value,trust_sell_value,dealer_proprietary_buy_value,dealer_proprietary_sell_value,dealer_hedge_buy_value,dealer_hedge_sell_value,dealer_buy_value,dealer_sell_value,date
0,264728792,445632508,258011910,366190980,728366700,617167100,986378610,983358080,2018-01-11

In [ ]:
from core.database.sources.participants.otc.market.foreign_trust_dealer_flow_value import version_5 as processor
import pathlib

root = pathlib.Path(
    '/Users/youming/Documents/personal/stocklab/DataHouse/data/backup/otc/institution_flow/market/url_1/1st'
)

# name = '20180115'
name = '20260430'

path = root.joinpath(name).with_suffix('.json')

content = processor.open(path)

raw_df = processor.to_df(content)

df = processor.standardize(content, path, False)

df.head(5)

# raw_df.loc[df.isna().any(axis=1), :]

,foreign_ex_dealer_buy_value,foreign_ex_dealer_sell_value,foreign_dealer_buy_value,foreign_dealer_sell_value,foreign_buy_value,foreign_sell_value,trust_buy_value,trust_sell_value,dealer_proprietary_buy_value,dealer_proprietary_sell_value,dealer_hedge_buy_value,dealer_hedge_sell_value,dealer_buy_value,dealer_sell_value,date
0,75688871862,84789311134,0,0,75688871862,84789311134,6500848430,4922077219,1613978761,2151461362,5084591809,4905571174,6698570570,7057032536,2026-04-30

In [ ]:
import pandas as pd
import requests

res = requests.get('https://openapi.tdcc.com.tw/v1/opendata/1-5')
data = res.json()

pd.DataFrame(data).set_index('證券代號').loc['1101  ']

       占集保庫存數比例%      人數     ﻿資料日期          股數 持股分級
證券代號
1101        0.27  147115  20260717    20858501    1
1101        6.92  236299  20260717   521246634    2
1101        5.90   59477  20260717   444504057    3
1101        3.96   24084  20260717   298228649    4
1101        3.20   13383  20260717   241286004    5
1101        4.25   12876  20260717   320365928    6
1101        2.73    5854  20260717   205947399    7
1101        2.36    3875  20260717   178140986    8
1101        6.22    6610  20260717   468458281    9
1101        5.13    2802  20260717   386397724   10
1101        4.03    1096  20260717   303408627   11
1101        1.83     285  20260717   138142023   12
1101        1.18     128  20260717    88922935   13
1101        1.04      87  20260717    78767847   14
1101       50.88     412  20260717  3828506147   15
1101        0.00       0  20260717           0   16
1101      100.00  514383  20260717  7523181742   17

In [ ]:
import pandas as pd

pd.Series([pd.NA,0])

0    <NA>
1     0.0
dtype: object

In [22]:
import re
re.sub(r'[^0-9.-]','','-1,123')

'-1123'